// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Winter_Project.Models;

#nullable disable

namespace Winter_Project.Migrations
{
    [DbContext(typeof(WinterContext))]
<<<<<<< HEAD:Migrations/20250218115846_InitialCreate.Designer.cs
<<<<<<<< HEAD:Migrations/20250217103619_UpdateUserModel.Designer.cs
    [Migration("20250217103619_UpdateUserModel")]
    partial class UpdateUserModel
========
    [Migration("20250218115846_InitialCreate")]
    partial class InitialCreate
>>>>>>>> 6ef0c2e64fb61f16f97868fd0afa280fdefac495:Migrations/20250218115846_InitialCreate.Designer.cs
=======
    [Migration("20250218144143_UpdateUserModel")]
    partial class UpdateUserModel
>>>>>>> 8f048c825d554849e56ec1ee590ccfc30ceb0bd2:Migrations/20250218144143_UpdateUserModel.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Winter_Project.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

<<<<<<<< HEAD:Migrations/20250217103619_UpdateUserModel.Designer.cs
========
                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

>>>>>>>> 6ef0c2e64fb61f16f97868fd0afa280fdefac495:Migrations/20250218115846_InitialCreate.Designer.cs
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

<<<<<<<< HEAD:Migrations/20250217103619_UpdateUserModel.Designer.cs
                    b.Property<string>("Name")
========
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
>>>>>>>> 6ef0c2e64fb61f16f97868fd0afa280fdefac495:Migrations/20250218115846_InitialCreate.Designer.cs
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
